# hwgen_alter_epoch
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_epoch/yosee/loss_log.txt' 
# hwgen_alter_fix_10
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/yosee/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/bear/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/bingpianshangping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/dradon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/goat/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/huaping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/luyiji/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/RedFlyDragon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_10/weiNi/loss_log.txt' 
# hwgen_alter_fix_50
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/yosee/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/bear/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/bingpianshangping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/dradon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/goat/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/huaping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/luyiji/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/RedFlyDragon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_fix_50/weiNi/loss_log.txt'
# hwgen_alter_w.o_blur
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/yosee/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/bear/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/bingpianshangping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/dradon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/goat/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/huaping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/luyiji/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/RedFlyDragon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_alter_w.o_blur/weiNi/loss_log.txt'
# hwgen_simul
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/yosee/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/bear/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/bingpianshangping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/dradon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/goat/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/huaping/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/luyiji/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/RedFlyDragon/loss_log.txt' 
python Plot_curve_from_loss_log.py '/media/eckert/My Passport/002PaperResults/Ablation/Results_strategy/hwgen_simul/weiNi/loss_log.txt'
